package enums

import "github.com/maestro-go/maestro/internal/conf"

type HookType int8

const (
	HOOK_REPEATABLE HookType = iota
	HOOK_REPEATABLE_DOWN

	HOOK_BEFORE
	HOOK_BEFORE_EACH
	HOOK_BEFORE_VERSION

	HOOK_AFTER
	HOOK_AFTER_EACH
	HOOK_AFTER_VERSION
)

var MapHookTypeToRegex = map[HookType]string{
	HOOK_REPEATABLE:      conf.HOOK_REPEATABLE_REGEX,
	HOOK_REPEATABLE_DOWN: conf.HOOK_REPEATABLE_DOWN_REGEX,

	HOOK_BEFORE:         conf.HOOK_BEFORE_REGEX,
	HOOK_BEFORE_EACH:    conf.HOOK_BEFORE_EACH_REGEX,
	HOOK_BEFORE_VERSION: conf.HOOK_BEFORE_VERSION_REGEX,

	HOOK_AFTER:         conf.HOOK_AFTER_REGEX,
	HOOK_AFTER_EACH:    conf.HOOK_AFTER_EACH_REGEX,
	HOOK_AFTER_VERSION: conf.HOOK_AFTER_VERSION_REGEX,
}
